### ISSUE TITLE
links at https://static.etherpad.org aren't working (for me)

### ISSUE THREAD

**Issue by ebardie** [ether/plugin-viewer#1]
The plugin links at
https://static.etherpad.org are all being mangled with an additional "%C2%AD"
after the underscore in their names. This is breaking the link when they hit
npmjs.com.

e.g. this (a real link from static.etherpad.org) gets 404ed:

	https://www.npmjs.com/package/ep_%C2%ADheadings2

whereas this works:

	https://www.npmjs.com/package/ep_headings2

**Comment by Gared** [comment]
You're right. I will fix this. Just FYI: This is a soft-hyphen to enable soft-breaks and should only be in plugin-name and (of course) not in npm-url
